import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import prisma from '../lib/prisma'
import DisplayVideos from '../components/DisplayVideos'

export const getStaticProps: GetStaticProps = async () => {
	const videos = await prisma.youtube_videos.findMany()
	return { props: { videos } }
}

export default function Home({ videos }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>YouTube Videos</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<DisplayVideos youtubeVideos={videos} />
			</main>
		</div>
	)
}
